### ISSUE TITLE
I feel dumb

### ISSUE THREAD

**Issue by cedric-marcone** [jaburns/js13k2020#2]
The only issue I have with 404kph is : I felt so dumb browsing your repo !

I really enjoyed reading your code and I learned a ton !
I oscillated form amazement to stupefaction, jumped from head scratching to aha moments. 
The verlet integration in the main fragment shader caught me off guard : a pure delight.

Thank you so much :)

**Comment by jaburns** [comment]
Haha thanks! Glad you enjoyed it! It's really just a big pile of little tricks I've picked up over the years.
